#!/usr/bin/env bash
#this is a script showing the configuration of a subdomain

funct ()
{
    Dom="$1"
    Sub="$2"
    dig "$Sub.$Dom" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$Sub"
}

for SUB in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$SUB" ] ;
    then
	funct "$1" "$SUB"
    fi
done