#!/usr/bin/env bash
#this script uses secure file copy to send a file to the remote server using arguments
if test $# -l 3;
then 
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
else
scp $1 $3@$2:$4;
fi
