#!/usr/bin/env bash
#this script installs ngnix using apt get then changes the port to 80 and runs a page
apt-get -y update
apt-get -y install nginx
sed -i '0,/listen .*/s//listen 80 default_server;/' /etc/nginx/sites-available/default
echo Holberton School > /var/www/html/index.nginx-debian.html
service nginx restart
