#!/usr/bin/env bash
#this script should install ngnix on the server and create a custom 404 page
Not_Found="error_page 404 /ERROR404.html;\n\t location = /ERROR404.html {\nroot /usr/share/nginx/html;\ninternal;\n}\n"
Page="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;\n\t}\n"
apt-get update
apt-get -y install nginx
sed -i '0,/listen .*/s//listen 80 default_server;/' /etc/nginx/sites-available/default
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "49i $Page" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/ERROR404.html
sed -i "25i $Not_Found" /etc/nginx/sites-available/default
service nginx restart
